name: John Haugaard
favicon: null
layout_spectrum: 0
typography_spectrum: 0.55979
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050505'
    - '#453c35'
    - '#d5cbb0'
    - '#847d6b'
    - '#2c6165'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.4375
  rhythmicContrast: 0
purpose:
  - name: stars
    item: ade965f4-3f17-4d06-8cf3-90dc932ce70c
    url: null
